version: 0.2
phases:
  install:
    commands:
      - echo Installing apache2
      - sudo apt install apache2 -y
  build:
    commands:
      - echo Build started on 'date'
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring apache2

artifacts:
  files:
    - /var/www/html/index.html      
