version: 0.2
phases:
  install:
    commands:
      - echo Installing apache
      - sudo apt-get install apache -y
  build:
    commands:
      - echo Build started on 'date'
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring Apache

artifacts:
  files:
    - /var/www/html/index.html      
